=== yldio/asap-hub/dev/fixtures/squidex/squidex/__json/app.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "AppModel",
  "type": "object",
  "required": [
    "clients",
    "roles",
    "languages",
    "contributors"
  ],
  "properties": {
    "clients": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/AppClientModel"
      }
    },
    "roles": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/AppRoleModel"
      }
    },
    "languages": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/UpdateLanguageDto"
      }
    },
    "contributors": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/AppContributorModel"
      }
    }
  },
  "definitions": {
    "AppClientModel": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "role"
      ],
      "properties": {
        "role": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    },
    "AppRoleModel": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "permissions"
      ],
      "properties": {
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "UpdateLanguageDto": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "isMaster": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "isOptional": {
          "type": "boolean"
        },
        "fallback": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          }
        }
      }
    },
    "AppContributorModel": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "role"
      ],
      "properties": {
        "role": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}

=== yldio/asap-hub/packages/squidex/schema/app.json
{
  "$schema": "./__json/app.json",
  "clients": {
    "default": {
      "role": "Owner",
      "name": "default"
    }
  },
  "roles": {
    "Developer": {
      "permissions": [
        "assets",
        "contents.*",
        "roles.read",
        "rules",
        "schemas",
        "workflows"
      ]
    },
    "Editor": {
      "permissions": ["assets", "contents.*", "roles.read", "workflows.read"]
    },
    "Owner": {
      "permissions": ["*"]
    },
    "Reader": {
      "permissions": ["assets.read", "contents.*.read"]
    }
  },
  "languages": {
    "en": {
      "isMaster": true,
      "isOptional": false,
      "fallback": []
    }
  },
  "contributors": {}
}

=== yldio/asap-hub/packages/squidex/schema/crn/__app.json
{
  "$schema": "./__json/app.json",
  "clients": {
    "test": {
      "role": "Owner",
      "name": null
    }
  },
  "roles": {
    "custom": {
      "permissions": ["schemas.*"]
    }
  },
  "languages": {
    "en": {
      "isMaster": true,
      "isOptional": false
    }
  },
  "contributors": {
    "sebastian@squidex.io": {
      "role": "Owner"
    }
  }
}
